import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';
type Direction = 'ltr' | 'rtl';

interface LanguageContextType {
  language: Language;
  direction: Direction;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.employees': 'Employees',
    'nav.attendance': 'Attendance',
    'nav.leaves': 'Leave Requests',
    'nav.salaries': 'Salaries',
    'nav.telegram': 'Telegram Bot',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    
    // Landing
    'landing.hero.title': 'Simple HR & Attendance Management',
    'landing.hero.subtitle': 'Track employee attendance, manage leaves, and calculate salaries — all in one place. With Telegram bot integration.',
    'landing.hero.cta': 'Start Free Trial',
    'landing.hero.login': 'Sign In',
    'landing.features.title': 'Everything you need',
    'landing.features.subtitle': 'A complete solution for small and medium businesses',
    
    // Features
    'feature.attendance': 'Attendance Tracking',
    'feature.attendance.desc': 'Employees check in/out via Telegram. No apps to install.',
    'feature.leaves': 'Leave Management',
    'feature.leaves.desc': 'Request and approve leaves with one click.',
    'feature.salaries': 'Salary Calculator',
    'feature.salaries.desc': 'Automatic calculations based on attendance and bonuses.',
    'feature.telegram': 'Telegram Bot',
    'feature.telegram.desc': 'Your team uses Telegram. No training needed.',
    
    // Auth
    'auth.login': 'Sign In',
    'auth.signup': 'Create Account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.company': 'Company Name',
    'auth.forgot': 'Forgot password?',
    'auth.no_account': "Don't have an account?",
    'auth.has_account': 'Already have an account?',
    'auth.fullName': 'Full Name',
    'auth.backToHome': 'Back to home',
    'auth.createWorkspace': 'Create your company workspace',
    'auth.signInWorkspace': 'Sign in to your workspace',
    'auth.manageTeam': 'Manage your team with ease',
    'auth.manageTeamDesc': 'Track attendance, approve leaves, and calculate salaries — all in one simple dashboard. Your team uses Telegram, no apps to install.',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.today': "Today's Overview",
    'dashboard.present': 'Present',
    'dashboard.absent': 'Absent',
    'dashboard.on_leave': 'On Break',
    'dashboard.pending': 'Pending Requests',
    'dashboard.whatsHappening': "Here's what's happening with your team today.",
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.manageEmployees': 'Manage Employees',
    'dashboard.manageEmployeesDesc': 'Add, edit, or remove team members',
    'dashboard.pendingLeaves': 'Pending Leave Requests',
    'dashboard.pendingLeavesDesc': 'Review and approve leave requests',
    'dashboard.viewAttendance': 'View Attendance',
    'dashboard.viewAttendanceDesc': "Today's check-ins and check-outs",
    'dashboard.telegramBot': 'Telegram Bot',
    'dashboard.telegramBotDesc': 'Connect your bot for employee check-ins',
    'dashboard.gettingStarted': 'Getting Started',
    'dashboard.welcomeMessage': 'Welcome to AttendEase! Here\'s how to get started:',
    'dashboard.step1': 'Add your first employees',
    'dashboard.step2': 'Connect your Telegram bot',
    'dashboard.step3': 'Share the bot link with your team',
    'dashboard.step4': 'Start tracking attendance!',
    'dashboard.totalEmployees': 'total employees',
    'dashboard.notCheckedIn': 'Not checked in today',
    'dashboard.currentlyOnBreak': 'Currently on break',
    'dashboard.currentlyPresent': 'Currently present',
    'dashboard.leaveRequests': 'Leave requests',
    'dashboard.view': 'View',
    'dashboard.review': 'Review',
    'dashboard.setup': 'Setup',
    
    // Employees
    'employees.title': 'Employees',
    'employees.add': 'Add Employee',
    'employees.search': 'Search employees...',
    'employees.role': 'Role',
    'employees.department': 'Department',
    'employees.status': 'Status',
    'employees.manage': 'Manage your team members, roles, and work schedules',
    'employees.noEmployees': 'No employees yet',
    'employees.getStarted': 'Get started by adding your first team member',
    'employees.fullName': 'Full Name',
    'employees.email': 'Email',
    'employees.salaryType': 'Salary Type',
    'employees.monthly': 'Monthly',
    'employees.daily': 'Daily',
    'employees.salaryAmount': 'Salary Amount',
    'employees.workSchedule': 'Work Schedule',
    'employees.workScheduleDesc': 'Set individual work hours for this employee',
    'employees.startTime': 'Start Time',
    'employees.endTime': 'End Time',
    'employees.breakDuration': 'Break (min)',
    'employees.weekendDays': 'Weekend Days',
    'employees.workHours': 'Work Hours',
    'employees.salary': 'Salary',
    'employees.deleteTitle': 'Delete Employee',
    'employees.deleteConfirm': 'Are you sure you want to delete this employee? This action cannot be undone.',
    'employees.editEmployee': 'Edit Employee',
    'employees.allStatus': 'All Status',
    'employees.basicInfo': 'Basic Information',
    'employees.salaryInfo': 'Salary Information',
    'employees.fullNamePlaceholder': 'John Doe',
    'employees.departmentPlaceholder': 'Engineering',
    'employees.addressPlaceholder': 'City, Street',
    'employees.notesPlaceholder': 'Additional notes about the employee...',
    'employees.currency': 'Currency',
    'employees.roleAdmin': 'Admin',
    'employees.roleManager': 'Manager',
    'employees.roleEmployee': 'Employee',
    'employees.position': 'Position',
    
    // Attendance
    'attendance.title': 'Attendance',
    'attendance.trackDaily': 'Track daily check-ins, breaks, and working hours',
    'attendance.checkedIn': 'Checked In',
    'attendance.checkedOut': 'Checked Out',
    'attendance.onBreak': 'On Break',
    'attendance.totalEmployees': 'Total Employees',
    'attendance.today': 'Today',
    'attendance.yesterday': 'Yesterday',
    'attendance.thisWeek': 'This Week',
    'attendance.thisMonth': 'This Month',
    'attendance.selectDate': 'Select date',
    'attendance.filterStatus': 'Filter status',
    'attendance.allStatus': 'All Status',
    'attendance.present': 'Present',
    'attendance.left': 'Left',
    'attendance.todayAttendance': "Today's Attendance",
    'attendance.noRecords': 'No attendance records today',
    'attendance.noRecordsDesc': 'Employees will appear here when they check in via Telegram',
    'attendance.employee': 'Employee',
    'attendance.checkIn': 'Check In',
    'attendance.checkOut': 'Check Out',
    
    // Leaves
    'leaves.title': 'Leave Requests',
    'leaves.manage': 'Review and manage leave requests',
    'leaves.pending': 'Pending',
    'leaves.approved': 'Approved',
    'leaves.rejected': 'Rejected',
    'leaves.pendingRequest': 'pending request',
    'leaves.pendingRequests': 'pending requests',
    'leaves.vacation': 'Vacation',
    'leaves.sick': 'Sick',
    'leaves.personal': 'Personal',
    'leaves.noRequests': 'No leave requests',
    'leaves.noRequestsDesc': 'Leave requests from employees will appear here',
    'leaves.employee': 'Employee',
    'leaves.type': 'Type',
    'leaves.duration': 'Duration',
    'leaves.reason': 'Reason',
    'leaves.actions': 'Actions',
    'leaves.day': 'day',
    'leaves.days': 'days',
    
    // Salaries
    'salaries.title': 'Salaries',
    'salaries.manage': 'View and manage monthly salary calculations',
    'salaries.exportReport': 'Export Report',
    'salaries.totalPayroll': 'Total Payroll',
    'salaries.totalBonuses': 'Total Bonuses',
    'salaries.totalDeductions': 'Total Deductions',
    'salaries.selectMonth': 'Select month',
    'salaries.filterStatus': 'Filter status',
    'salaries.allStatus': 'All Status',
    'salaries.paid': 'Paid',
    'salaries.pending': 'Pending',
    'salaries.processing': 'Processing',
    'salaries.breakdown': 'Salary Breakdown',
    'salaries.employee': 'Employee',
    'salaries.workDays': 'Work Days',
    'salaries.baseSalary': 'Base Salary',
    'salaries.bonus': 'Bonus',
    'salaries.deductions': 'Deductions',
    'salaries.netSalary': 'Net Salary',
    
    // Telegram
    'telegram.title': 'Telegram Bot',
    'telegram.description': 'Connect your Telegram bot to enable employee check-ins via Telegram',
    'telegram.secureStorage': 'Secure Token Storage',
    'telegram.secureDesc': 'Your Telegram bot token is stored securely using encrypted secrets management. Tokens are never exposed in the database or client-side code.',
    'telegram.connected': 'Connected',
    'telegram.notConnected': 'Not Connected',
    'telegram.botTitle': 'Telegram Bot',
    'telegram.botDesc': "Your company's dedicated attendance bot",
    'telegram.active': 'Bot is active and ready!',
    'telegram.activeDesc': 'Your employees can now check in/out, start/end breaks, and request leave via Telegram.',
    'telegram.disconnect': 'Disconnect Bot',
    'telegram.setupTitle': 'Setup Instructions',
    'telegram.step1': 'Create a bot on Telegram via',
    'telegram.step2': 'Copy your bot token (keep it secret!)',
    'telegram.step3': 'Contact our support to securely connect your bot',
    'telegram.step4': 'Share the bot link with your employees',
    'telegram.requestSetup': 'Request Bot Setup',
    'telegram.howItWorks': 'How it works',
    'telegram.howItWorksDesc': 'Simple button-based interactions for your employees',
    'telegram.checkInOut': 'Check In / Out',
    'telegram.checkInOutDesc': 'Employees tap a button to clock in or out',
    'telegram.breakManagement': 'Break Management',
    'telegram.breakManagementDesc': 'Start and end breaks with a single tap',
    'telegram.leaveRequests': 'Leave Requests',
    'telegram.leaveRequestsDesc': 'Request time off directly through the bot',
    'telegram.adminNotifications': 'Admin Notifications',
    'telegram.adminNotificationsDesc': 'Get notified of attendance events instantly',
    'telegram.preview': 'Employee Bot Preview',
    'telegram.previewDesc': 'What your employees will see in Telegram',
    'telegram.greeting': 'Good morning! Ready to start your day?',
    'telegram.btnCheckIn': 'Check In',
    'telegram.btnCheckOut': 'Check Out',
    'telegram.btnStartBreak': 'Start Break',
    'telegram.btnEndBreak': 'End Break',
    'telegram.btnRequestLeave': 'Request Leave',
    
    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.theme.light': 'Light',
    'settings.theme.dark': 'Dark',
    'settings.managePreferences': 'Manage your workspace preferences',
    'settings.displayLanguage': 'Display Language',
    'settings.currentDirection': 'Current direction',
    'settings.darkMode': 'Dark Mode',
    'settings.switchTheme': 'Switch between light and dark themes',
    'settings.companyInfo': 'Company Information',
    'settings.updateCompany': 'Update your company details',
    'settings.companyName': 'Company Name',
    'settings.timezone': 'Timezone',
    'settings.workingHours': 'Default Working Hours',
    'settings.workingHoursDesc': 'Set default working hours for all employees. You can override these for individual employees.',
    'settings.workStart': 'Work Start',
    'settings.workEnd': 'Work End',
    'settings.breakDuration': 'Break Duration (min)',
    'settings.weekendDays': 'Default Weekend Days',
    'settings.weekendDaysDesc': 'Select which days are considered weekends. These can be customized per employee.',
    'settings.weekendNote': 'Note: Weekend settings are saved per employee when you edit them individually.',
    'settings.languageDesc': 'Choose your preferred language. Arabic will enable RTL layout.',
    'settings.themeDesc': 'Customize the appearance of the application',
    'settings.defaultCurrency': 'Default Currency',
    'settings.defaultCurrencyDesc': 'This currency will be used by default for new employees',
    
    // Common
    'common.actions': 'Actions',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.unknown': 'Unknown',
    'common.noData': 'No data',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.sunday': 'Sunday',
    'common.monday': 'Monday',
    'common.tuesday': 'Tuesday',
    'common.wednesday': 'Wednesday',
    'common.thursday': 'Thursday',
    'common.friday': 'Friday',
    'common.saturday': 'Saturday',
    'common.sun': 'Sun',
    'common.mon': 'Mon',
    'common.tue': 'Tue',
    'common.wed': 'Wed',
    'common.thu': 'Thu',
    'common.fri': 'Fri',
    'common.sat': 'Sat',

    // Employee Details
    'employeeDetails.notFound': 'Employee not found',
    'employeeDetails.backToList': 'Back to list',
    'employeeDetails.thisWeek': 'This Week',
    'employeeDetails.thisMonth': 'This Month',
    'employeeDetails.thisYear': 'This Year',
    'employeeDetails.attendanceDays': 'Attendance Days',
    'employeeDetails.absentDays': 'Absent Days',
    'employeeDetails.totalHours': 'Total Hours',
    'employeeDetails.hours': 'hours',
    'employeeDetails.commitmentRate': 'Commitment Rate',
    'employeeDetails.personalInfo': 'Personal Info',
    'employeeDetails.attendanceLog': 'Attendance Log',
    'employeeDetails.salaryInfo': 'Salary Info',
    'employeeDetails.phone': 'Phone',
    'employeeDetails.nationalId': 'National ID',
    'employeeDetails.hireDate': 'Hire Date',
    'employeeDetails.address': 'Address',
    'employeeDetails.notes': 'Notes',
    'employeeDetails.noAttendance': 'No attendance records',
    'employeeDetails.lateArrivals': 'Late Arrivals',

    // Employee Form Extended
    'employees.phone': 'Phone',
    'employees.nationalId': 'National ID',
    'employees.address': 'Address',
    'employees.hireDate': 'Hire Date',
    'employees.notes': 'Notes',
    'employees.additionalInfo': 'Additional Info',
    'employees.viewDetails': 'View Details',
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.employees': 'الموظفين',
    'nav.attendance': 'الحضور',
    'nav.leaves': 'طلبات الإجازة',
    'nav.salaries': 'الرواتب',
    'nav.telegram': 'بوت تيليجرام',
    'nav.settings': 'الإعدادات',
    'nav.logout': 'تسجيل الخروج',
    
    // Landing
    'landing.hero.title': 'إدارة الموارد البشرية والحضور بسهولة',
    'landing.hero.subtitle': 'تتبع حضور الموظفين، وإدارة الإجازات، وحساب الرواتب — كل ذلك في مكان واحد. مع تكامل بوت تيليجرام.',
    'landing.hero.cta': 'ابدأ تجربة مجانية',
    'landing.hero.login': 'تسجيل الدخول',
    'landing.features.title': 'كل ما تحتاجه',
    'landing.features.subtitle': 'حل متكامل للشركات الصغيرة والمتوسطة',
    
    // Features
    'feature.attendance': 'تتبع الحضور',
    'feature.attendance.desc': 'يسجل الموظفون حضورهم عبر تيليجرام. لا حاجة لتثبيت تطبيقات.',
    'feature.leaves': 'إدارة الإجازات',
    'feature.leaves.desc': 'طلب والموافقة على الإجازات بنقرة واحدة.',
    'feature.salaries': 'حاسبة الرواتب',
    'feature.salaries.desc': 'حسابات تلقائية بناءً على الحضور والمكافآت.',
    'feature.telegram': 'بوت تيليجرام',
    'feature.telegram.desc': 'فريقك يستخدم تيليجرام. لا حاجة للتدريب.',
    
    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.company': 'اسم الشركة',
    'auth.forgot': 'نسيت كلمة المرور؟',
    'auth.no_account': 'ليس لديك حساب؟',
    'auth.has_account': 'لديك حساب بالفعل؟',
    'auth.fullName': 'الاسم الكامل',
    'auth.backToHome': 'العودة للرئيسية',
    'auth.createWorkspace': 'إنشاء مساحة عمل شركتك',
    'auth.signInWorkspace': 'تسجيل الدخول لمساحة العمل',
    'auth.manageTeam': 'أدر فريقك بسهولة',
    'auth.manageTeamDesc': 'تتبع الحضور، واعتمد الإجازات، واحسب الرواتب — كل ذلك في لوحة تحكم بسيطة. فريقك يستخدم تيليجرام، لا حاجة لتثبيت تطبيقات.',
    
    // Dashboard
    'dashboard.welcome': 'مرحباً بعودتك',
    'dashboard.today': 'نظرة عامة على اليوم',
    'dashboard.present': 'حاضر',
    'dashboard.absent': 'غائب',
    'dashboard.on_leave': 'في استراحة',
    'dashboard.pending': 'طلبات معلقة',
    'dashboard.whatsHappening': 'إليك ما يحدث مع فريقك اليوم.',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.manageEmployees': 'إدارة الموظفين',
    'dashboard.manageEmployeesDesc': 'إضافة أو تعديل أو حذف أعضاء الفريق',
    'dashboard.pendingLeaves': 'طلبات الإجازة المعلقة',
    'dashboard.pendingLeavesDesc': 'مراجعة واعتماد طلبات الإجازة',
    'dashboard.viewAttendance': 'عرض الحضور',
    'dashboard.viewAttendanceDesc': 'تسجيلات الدخول والخروج اليوم',
    'dashboard.telegramBot': 'بوت تيليجرام',
    'dashboard.telegramBotDesc': 'ربط البوت لتسجيل حضور الموظفين',
    'dashboard.gettingStarted': 'البدء',
    'dashboard.welcomeMessage': 'مرحباً بك في AttendEase! إليك كيفية البدء:',
    'dashboard.step1': 'أضف موظفيك الأوائل',
    'dashboard.step2': 'اربط بوت تيليجرام',
    'dashboard.step3': 'شارك رابط البوت مع فريقك',
    'dashboard.step4': 'ابدأ تتبع الحضور!',
    'dashboard.totalEmployees': 'إجمالي الموظفين',
    'dashboard.notCheckedIn': 'لم يسجل الحضور اليوم',
    'dashboard.currentlyOnBreak': 'في استراحة حالياً',
    'dashboard.currentlyPresent': 'حاضر حالياً',
    'dashboard.leaveRequests': 'طلبات الإجازة',
    'dashboard.view': 'عرض',
    'dashboard.review': 'مراجعة',
    'dashboard.setup': 'إعداد',
    
    // Employees
    'employees.title': 'الموظفين',
    'employees.add': 'إضافة موظف',
    'employees.search': 'البحث عن موظفين...',
    'employees.role': 'الدور',
    'employees.department': 'القسم',
    'employees.status': 'الحالة',
    'employees.manage': 'إدارة أعضاء الفريق والأدوار وجداول العمل',
    'employees.noEmployees': 'لا يوجد موظفين بعد',
    'employees.getStarted': 'ابدأ بإضافة أول عضو في الفريق',
    'employees.fullName': 'الاسم الكامل',
    'employees.email': 'البريد الإلكتروني',
    'employees.salaryType': 'نوع الراتب',
    'employees.monthly': 'شهري',
    'employees.daily': 'يومي',
    'employees.salaryAmount': 'مبلغ الراتب',
    'employees.workSchedule': 'جدول العمل',
    'employees.workScheduleDesc': 'تحديد ساعات العمل الفردية لهذا الموظف',
    'employees.startTime': 'وقت البدء',
    'employees.endTime': 'وقت الانتهاء',
    'employees.breakDuration': 'الاستراحة (دقيقة)',
    'employees.weekendDays': 'أيام العطلة',
    'employees.workHours': 'ساعات العمل',
    'employees.salary': 'الراتب',
    'employees.deleteTitle': 'حذف الموظف',
    'employees.deleteConfirm': 'هل أنت متأكد من حذف هذا الموظف؟ لا يمكن التراجع عن هذا الإجراء.',
    'employees.editEmployee': 'تعديل الموظف',
    'employees.allStatus': 'جميع الحالات',
    'employees.basicInfo': 'المعلومات الأساسية',
    'employees.salaryInfo': 'معلومات الراتب',
    'employees.fullNamePlaceholder': 'أحمد محمد',
    'employees.departmentPlaceholder': 'الهندسة',
    'employees.addressPlaceholder': 'المدينة، الشارع',
    'employees.notesPlaceholder': 'ملاحظات إضافية عن الموظف...',
    'employees.currency': 'العملة',
    'employees.roleAdmin': 'مدير',
    'employees.roleManager': 'مشرف',
    'employees.roleEmployee': 'موظف',
    'employees.position': 'المنصب',
    
    // Attendance
    'attendance.title': 'الحضور',
    'attendance.trackDaily': 'تتبع تسجيلات الدخول والاستراحات وساعات العمل اليومية',
    'attendance.checkedIn': 'مسجل الدخول',
    'attendance.checkedOut': 'مسجل الخروج',
    'attendance.onBreak': 'في استراحة',
    'attendance.totalEmployees': 'إجمالي الموظفين',
    'attendance.today': 'اليوم',
    'attendance.yesterday': 'أمس',
    'attendance.thisWeek': 'هذا الأسبوع',
    'attendance.thisMonth': 'هذا الشهر',
    'attendance.selectDate': 'اختر التاريخ',
    'attendance.filterStatus': 'فلترة الحالة',
    'attendance.allStatus': 'جميع الحالات',
    'attendance.present': 'حاضر',
    'attendance.left': 'غادر',
    'attendance.todayAttendance': 'حضور اليوم',
    'attendance.noRecords': 'لا توجد سجلات حضور اليوم',
    'attendance.noRecordsDesc': 'سيظهر الموظفون هنا عند تسجيل الدخول عبر تيليجرام',
    'attendance.employee': 'الموظف',
    'attendance.checkIn': 'تسجيل الدخول',
    'attendance.checkOut': 'تسجيل الخروج',
    
    // Leaves
    'leaves.title': 'طلبات الإجازة',
    'leaves.manage': 'مراجعة وإدارة طلبات الإجازة',
    'leaves.pending': 'معلق',
    'leaves.approved': 'موافق عليه',
    'leaves.rejected': 'مرفوض',
    'leaves.pendingRequest': 'طلب معلق',
    'leaves.pendingRequests': 'طلبات معلقة',
    'leaves.vacation': 'إجازة',
    'leaves.sick': 'مرضية',
    'leaves.personal': 'شخصية',
    'leaves.noRequests': 'لا توجد طلبات إجازة',
    'leaves.noRequestsDesc': 'ستظهر طلبات الإجازة من الموظفين هنا',
    'leaves.employee': 'الموظف',
    'leaves.type': 'النوع',
    'leaves.duration': 'المدة',
    'leaves.reason': 'السبب',
    'leaves.actions': 'الإجراءات',
    'leaves.day': 'يوم',
    'leaves.days': 'أيام',
    
    // Salaries
    'salaries.title': 'الرواتب',
    'salaries.manage': 'عرض وإدارة حسابات الرواتب الشهرية',
    'salaries.exportReport': 'تصدير التقرير',
    'salaries.totalPayroll': 'إجمالي الرواتب',
    'salaries.totalBonuses': 'إجمالي المكافآت',
    'salaries.totalDeductions': 'إجمالي الخصومات',
    'salaries.selectMonth': 'اختر الشهر',
    'salaries.filterStatus': 'فلترة الحالة',
    'salaries.allStatus': 'جميع الحالات',
    'salaries.paid': 'مدفوع',
    'salaries.pending': 'معلق',
    'salaries.processing': 'قيد المعالجة',
    'salaries.breakdown': 'تفاصيل الرواتب',
    'salaries.employee': 'الموظف',
    'salaries.workDays': 'أيام العمل',
    'salaries.baseSalary': 'الراتب الأساسي',
    'salaries.bonus': 'المكافأة',
    'salaries.deductions': 'الخصومات',
    'salaries.netSalary': 'صافي الراتب',
    
    // Telegram
    'telegram.title': 'بوت تيليجرام',
    'telegram.description': 'اربط بوت تيليجرام لتمكين تسجيل حضور الموظفين عبر تيليجرام',
    'telegram.secureStorage': 'تخزين آمن للرمز',
    'telegram.secureDesc': 'يتم تخزين رمز بوت تيليجرام بشكل آمن باستخدام إدارة الأسرار المشفرة. لا يتم كشف الرموز في قاعدة البيانات أو الكود.',
    'telegram.connected': 'متصل',
    'telegram.notConnected': 'غير متصل',
    'telegram.botTitle': 'بوت تيليجرام',
    'telegram.botDesc': 'بوت الحضور المخصص لشركتك',
    'telegram.active': 'البوت نشط وجاهز!',
    'telegram.activeDesc': 'يمكن لموظفيك الآن تسجيل الدخول/الخروج وبدء/إنهاء الاستراحات وطلب الإجازة عبر تيليجرام.',
    'telegram.disconnect': 'فصل البوت',
    'telegram.setupTitle': 'تعليمات الإعداد',
    'telegram.step1': 'أنشئ بوت على تيليجرام عبر',
    'telegram.step2': 'انسخ رمز البوت (احتفظ به سرياً!)',
    'telegram.step3': 'تواصل مع الدعم لربط البوت بشكل آمن',
    'telegram.step4': 'شارك رابط البوت مع موظفيك',
    'telegram.requestSetup': 'طلب إعداد البوت',
    'telegram.howItWorks': 'كيف يعمل',
    'telegram.howItWorksDesc': 'تفاعلات بسيطة بالأزرار لموظفيك',
    'telegram.checkInOut': 'تسجيل الدخول / الخروج',
    'telegram.checkInOutDesc': 'يضغط الموظفون على زر لتسجيل الدخول أو الخروج',
    'telegram.breakManagement': 'إدارة الاستراحات',
    'telegram.breakManagementDesc': 'بدء وإنهاء الاستراحات بضغطة واحدة',
    'telegram.leaveRequests': 'طلبات الإجازة',
    'telegram.leaveRequestsDesc': 'طلب إجازة مباشرة عبر البوت',
    'telegram.adminNotifications': 'إشعارات المسؤول',
    'telegram.adminNotificationsDesc': 'احصل على إشعارات فورية بأحداث الحضور',
    'telegram.preview': 'معاينة بوت الموظفين',
    'telegram.previewDesc': 'ما سيراه موظفوك في تيليجرام',
    'telegram.greeting': 'صباح الخير! جاهز لبدء يومك؟',
    'telegram.btnCheckIn': '✅ تسجيل الدخول',
    'telegram.btnCheckOut': '🚪 تسجيل الخروج',
    'telegram.btnStartBreak': '☕ بدء الاستراحة',
    'telegram.btnEndBreak': '💼 إنهاء الاستراحة',
    'telegram.btnRequestLeave': '📅 طلب إجازة',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.language': 'اللغة',
    'settings.theme': 'المظهر',
    'settings.theme.light': 'فاتح',
    'settings.theme.dark': 'داكن',
    'settings.managePreferences': 'إدارة تفضيلات مساحة العمل',
    'settings.displayLanguage': 'لغة العرض',
    'settings.currentDirection': 'الاتجاه الحالي',
    'settings.darkMode': 'الوضع الداكن',
    'settings.switchTheme': 'التبديل بين المظهر الفاتح والداكن',
    'settings.companyInfo': 'معلومات الشركة',
    'settings.updateCompany': 'تحديث تفاصيل الشركة',
    'settings.companyName': 'اسم الشركة',
    'settings.timezone': 'المنطقة الزمنية',
    'settings.workingHours': 'ساعات العمل الافتراضية',
    'settings.workingHoursDesc': 'تحديد ساعات العمل الافتراضية لجميع الموظفين. يمكنك تخصيصها لكل موظف.',
    'settings.workStart': 'بداية العمل',
    'settings.workEnd': 'نهاية العمل',
    'settings.breakDuration': 'مدة الاستراحة (دقيقة)',
    'settings.weekendDays': 'أيام العطلة الافتراضية',
    'settings.weekendDaysDesc': 'اختر الأيام التي تعتبر عطلة. يمكن تخصيصها لكل موظف.',
    'settings.weekendNote': 'ملاحظة: يتم حفظ إعدادات العطلة لكل موظف عند تعديله.',
    'settings.languageDesc': 'اختر لغتك المفضلة. العربية ستفعل التخطيط من اليمين لليسار.',
    'settings.themeDesc': 'تخصيص مظهر التطبيق',
    'settings.defaultCurrency': 'العملة الافتراضية',
    'settings.defaultCurrencyDesc': 'هذه العملة ستستخدم افتراضياً للموظفين الجدد',
    
    // Common
    'common.actions': 'الإجراءات',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.active': 'نشط',
    'common.inactive': 'غير نشط',
    'common.unknown': 'غير معروف',
    'common.noData': 'لا توجد بيانات',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    'common.sunday': 'الأحد',
    'common.monday': 'الإثنين',
    'common.tuesday': 'الثلاثاء',
    'common.wednesday': 'الأربعاء',
    'common.thursday': 'الخميس',
    'common.friday': 'الجمعة',
    'common.saturday': 'السبت',
    'common.sun': 'أحد',
    'common.mon': 'إثن',
    'common.tue': 'ثلا',
    'common.wed': 'أرب',
    'common.thu': 'خمي',
    'common.fri': 'جمع',
    'common.sat': 'سبت',

    // Employee Details
    'employeeDetails.notFound': 'الموظف غير موجود',
    'employeeDetails.backToList': 'العودة للقائمة',
    'employeeDetails.thisWeek': 'هذا الأسبوع',
    'employeeDetails.thisMonth': 'هذا الشهر',
    'employeeDetails.thisYear': 'هذه السنة',
    'employeeDetails.attendanceDays': 'أيام الحضور',
    'employeeDetails.absentDays': 'أيام الغياب',
    'employeeDetails.totalHours': 'إجمالي الساعات',
    'employeeDetails.hours': 'ساعة',
    'employeeDetails.commitmentRate': 'نسبة الالتزام',
    'employeeDetails.personalInfo': 'المعلومات الشخصية',
    'employeeDetails.attendanceLog': 'سجل الحضور',
    'employeeDetails.salaryInfo': 'معلومات الراتب',
    'employeeDetails.phone': 'رقم الهاتف',
    'employeeDetails.nationalId': 'رقم الهوية',
    'employeeDetails.hireDate': 'تاريخ التعيين',
    'employeeDetails.address': 'العنوان',
    'employeeDetails.notes': 'ملاحظات',
    'employeeDetails.noAttendance': 'لا توجد سجلات حضور',
    'employeeDetails.lateArrivals': 'مرات التأخير',

    // Employee Form Extended
    'employees.phone': 'رقم الهاتف',
    'employees.nationalId': 'رقم الهوية',
    'employees.address': 'العنوان',
    'employees.hireDate': 'تاريخ التعيين',
    'employees.notes': 'ملاحظات',
    'employees.additionalInfo': 'معلومات إضافية',
    'employees.viewDetails': 'عرض التفاصيل',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('ar');
  const direction: Direction = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && (saved === 'en' || saved === 'ar')) {
      setLanguageState(saved);
    }
  }, []);

  useEffect(() => {
    document.documentElement.dir = direction;
    document.documentElement.lang = language;
    localStorage.setItem('language', language);
  }, [language, direction]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, direction, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
